- docs/get-started.mdx
- docs/tutorials/like-repost.mdx
@emilyliu7321 I have released a new SDK version with small API changes to align with the typescript agent
> Update Python code snippets

- docs/tutorials/blocking.mdx
- docs/tutorials/custom-feeds.mdx
- docs/tutorials/like-repost.mdx
- docs/tutorials/thread-gates.mdx
@emilyliu7321 almost all tutorials are covered with Python code snippets 🎊 
leftovers:
- profile editing (i wanna provide more user friendly API first)
- user lists (huuuuge page)
> Add more Python code snippets

- src/data/users.tsx
Added 'opensource' tag and source pointer to client repository for Blue Wrapper.
> Update details for Blue Wrapper in Community Showcase

- src/data/users.tsx
Please allow me to register the client I am creating.
> Add a client to showcase

- docs/tutorials/viewing-threads.mdx
> Fix broken Markdown typo

- src/data/users.tsx
This PR adds Ouranos to community showcase. 🌸
> Add Ouranos to community showcase

- LICENSE.txt
This small PR updates the copyright year in the LICENSE.txt file.
> Update copyright year in LICENSE.txt

- src/data/users.tsx
[ATrium](https://github.com/sugyan/atrium) is an AT Protocol implementation in Rust.
I've also submitted a pull-request as an SDK addition in #64, but if you decide it's not appropriate, please close it.
> Add ATrium to community showcase

- blog/2024-03-06-atproto-grants.md
adds blog post announcing AT Protocol grants
> Add atproto grants announcement blog

- src/data/users.tsx
Add bot that posts Merriam Webster's word of the day
> Add word of the day bot to showcase

- docs/advanced-guides/moderation.md
For the new 3p labelers system
> Updated moderation advanced guide

- src/data/users.tsx
Add ATProto Export to Showcase
> Add ATProto Export to Showcase

- src/data/users.tsx
a simple Go module to create Bsky Bots : https://github.com/danrusei/gobot-bsky
> adding in the community list a Go lib to create Bsky Bots

- blog/2024-04-23-atproto-grants-recipients.md
blog post that announces the second batch of atproto grant recipients
> Add grant recipients blog

- README.md
- atproto-openapi-types/lib/converters/object.ts
- atproto-openapi-types/spec/api.json
- docs/api/app-bsky-feed-send-interactions.api.mdx
Works around upstream issue filed here: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/813
> fix the build

- src/data/users.tsx
[swift-atproto](https://github.com/nnabeyang/swift-atproto) is an AT Protocol implementation in Swift.
> Add swift-atproto to community showcase

- blog/2023-06-20-federation-sandbox.md
- docs/advanced-guides/federation-architecture.md
https://github.com/bluesky-social/atproto/discussions/2610
> sandbox removal

- blog/2023-11-06-repo-export.md
> fix old repo export blog command name

- docs/advanced-guides/moderation.md
Adjusts the other part of the sentence from #161.
> Update number of additional subscriptions in moderation.md

- docs/advanced-guides/oauth-client.md
[Rendered doc](https://github.com/bluesky-social/bsky-docs/blob/bnewbold/oauth-client-guide/docs/advanced-guides/oauth-client.md)
Don't have any known issues, but could use a copy edit, and might need to be fleshed out in a couple places.
> OAuth client implementation advanced guide

- src/data/users.tsx
adding https://github.com/itaru2622/bluesky-selfhost-env to showcase
> Add "Bluesky Self Hosting Tool" to showcase

- docs/starter-templates/clients.mdx
Small PR to clarify what this page is about: it is about making web apps for the Bluesky app/lexicons, not implementing low-level API clients.
> clarify 'Clients' starter template title

- Makefile
- README.md
@emilyliu7321 re-wrote most of the earlier README, but i'm guessing a bunch of that was from a docusaurus template
The Makefile is our standard Makefile template.
basically I just keep forgetting the specific commands to run in this repo!
> update README; add Makefile

- docusaurus.config.js
- package-lock.json
- package.json
This pulls a single commit from @sugyan's comment here:
https://github.com/bluesky-social/bsky-docs/issues/246#issuecomment-2494017987
> Update docusaurus, plugins

- docs/tutorials/user-lists.mdx
> Fix typo "bloced" -> "blocked" in user-lists.mdx

- docs/advanced-guides/posts.md
I'm not a Python pro so this is my best guess at how it would be done
> Suggest including aspectRatio in the posting guide

- docs/starter-templates/custom-feeds.mdx
> Update custom feeds doc to say it goes though AppView

- .github/workflows/generate_schema.yaml
Will keep this commented out for now, but want it disabled in a way that doesn't break CI.
> fix github workflow yaml syntax

- blog/2025-03-07-2025-protocol-roadmap-spring.md
adds a needed space and removes an extra comma.
> fix: typos

- blog/2024-03-06-atproto-grants.md
- blog/2024-04-23-atproto-grants-recipients.md
- blog/2024-05-15-label-grants.md
Don't want folks coming across these and submitting new applications in 2025.
> remove 2024 grant application forms

- docs/advanced-guides/firehose.mdx
Replaced the TODO to add lexicon link with the ATProto lexicon link. I also added a simplified Python version at the end. I could not make the go version work because its missing imports that are specific to bluesky repos. Had trouble finding them. Python websocket connection took me like 2 minutes.
> Replace TODO with link + add more docs to firehose.mdx

- docs/advanced-guides/custom-schemas.mdx
> Fixed Typo in custom-schemas.mdx

- atproto-openapi-types/main.ts
- blog/2023-08-11-create-post.md
- docs/advanced-guides/custom-schemas.mdx
- docs/advanced-guides/posts.md
- docs/advanced-guides/service-auth.mdx
- docs/tutorials/creating-a-post.mdx
These are an updated subset of https://github.com/bluesky-social/bsky-docs/pull/240
> typo fixes

- docs/advanced-guides/rate-limits.md
Closes: https://github.com/bluesky-social/bsky-docs/issues/324
> fix typo in rate-limits

- docs/tutorials/video.mdx
This is @mozzius work. Thanks!
Creating this as a PR now so we can link folks to it. Some more context needed before publishing:
> video tutorial

- docs/tutorials/video.mdx
> Use Tangled Strings instead of GitHub Gists
